### ISSUE TITLE
Other database providers

### ISSUE THREAD

**Issue by rizzla22** [dhax/go-base#12]
Id love to use this with mongodb it would be great if there was an example or some db abstraction to make it easy to plug in another type

**Comment by dhax** [comment]
Hi, the database actions are actually abstracted into interfaces, so you could quite easily swap to MongoDB just by implementing these interfaces using a MongoDB "Store" and passing this to e.g. NewAccountResource(store AccountStore). The AccountResource itself doesn't know how AccountStore is actually implemented, it just uses the methods defined in the interface in api/app/account.go.

So currently database.NewAccountStore returns a go-pg store, which implements the AccountStore interface methods. You don't need to change this package, just create new mongodb package with NewAccountStore(db *mongo.Client) which takes a mongoDB connection and implements all methods defined in the interface but using mongoDB instead of go-pg.
The structure is the same, so you could basically just copy/duplicate the current database package (rename to mongodb or so) and change every occurrence of go-pg to use mongoDB connection.

I am closing this for now as it's not an issue, but feel free to ask if anything is unclear.
