### ISSUE TITLE
create go-base.yaml

### ISSUE THREAD

**Issue by zanjs** [dhax/go-base#2]
Did not find  go-base.yaml boilerplate

**Comment by dhax** [comment]
This is the default setup you get by using cobra for project setup. The path for the config file is by cobra's default your $HOME directory. I left it like that because a config file is not necessary to run this boiler as all required config values have defaults set. I would leave it to the user to then further adapt the config strategy to his needs, i.e. move the config file to an appropriate location or just don't use one at all and stay with env vars.

**Comment by karfianto** [comment]
at least you can provide .env.example file or .go-base.example just to make it easier to write or change default config

**Comment by dhax** [comment]
that's simply a violation of 12 factor app and not best practice... coding is not supposed to be easy in every aspect ;)
